# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run Deno lint and test.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@004814556e37c54a2f6e31384c9e18e9833173669
        with:
          deno-version: v1.x

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      # - name: Verify formatting
      #   run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Compile Linux
        run: deno compile --allow-all --target x86_64-unknown-linux-gnu -o inncloud-linux main.ts

      - name: Compile Windows
        run: deno compile --allow-all --target x86_64-pc-windows-msvc -o inncloud-windows.exe main.ts
      
      - name: Compile macOS
        run: deno compile --allow-all --target x86_64-apple-darwin -o inncloud-macos main.ts
      
      - name: Compile macOS ARM
        run: deno compile --allow-all --target aarch64-apple-darwin -o inncloud-macos-arm main.ts
      
      - name: Upload Inncloud Linux
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Inncloud Linux
          path: inncloud-linux

      - name: Upload Inncloud Windows
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Inncloud Windows
          path: inncloud-windows.exe
          
      - name: Upload Inncloud macOS
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Inncloud macOS
          path: inncloud-macos
          
      - name: Upload Inncloud macOS ARM
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Inncloud macOS ARM
          path: inncloud-macos-arm

